---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Install packages
    package:
      name:
        - xorg
        - cowsay
        - xorg-xinit
        - xorg-server
        - xorg-server-xephyr
        - htop
        - nano
        - neofetch
        - lightdm
        - lightdm-gtk-greeter
        - sddm
        - qtile
        - xterm
        - picom
        - kitty
        - dconf-editor
        - nitrogen
        - xf86-video-fbdev
        - firefox
        - virtualbox-guest-utils
        - base-devel
        - net-tools
        - python-pip

  - name: Enabling lightdm
    service:
      name: lightdm
      enabled: yes

  - name: Enable vboxutils
    service:
      name: vboxservice
      enabled: yes

  - name: Set graphical target lightdm
    command: systemctl set-default graphical.target

  
  - name: Create the aur_builder user
    become: yes
    ansible.builtin.user:
      name: aur_builder
      create_home: yes
      group: wheel

  - name: Allow the aur_builder user to run sudo pacman without a password
    become: yes
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/11-install-aur_builder
      line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      validate: 'visudo -cf %s'
  
  - name: Install aur packages
    aur:
      use: yay
      name:
        - nerd-fonts-ubuntu-mono
