---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - xorg
        - xinit
        - htop
        - neofetch
        - lightdm
        - sddm
        - qtile
        - xterm
        - picom
        - kitty
        - dconf-editor

  - name: Enabling lightdm
    service:
      name: lightdm
      enabled: yes