---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - neofetch
        - lightdm

  - name: Enabling lightdm
    service:
      name: lightdm
      enabled: yes