---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - neofetch
        - tmuxhttps://github.com/victoralexander132/ansible-arch.git