---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Install packages
    package:
      name:
        - xorg
        - cowsay
        - xorg-xinit
        - xorg-server
        - xorg-server-xephyr
        - htop
        - nano
        - neofetch
        - lightdm
        - lightdm-gtk-greeter
        - sddm
        - qtile
        - xterm
        - picom
        - kitty
        - dconf-editor
        - nitrogen
        - xf86-video-fbdev
        - firefox
        - virtualbox-guest-utils
        - base-devel
        - net-tools
        - python-pip


  - name: Enabling lightdm
    service:
      name: lightdm
      enabled: yes

  - name: Enable vboxutils
    service:
      name: vboxservice
      enabled: yes

  - name: Set graphical target lightdm
    command: systemctl set-default graphical.target

  - user: name=aur_builder
  
  - lineinfile:
       path: /etc/sudoers.d/aur_builder-allow-to-sudo-pacman
       state: present
       line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
       validate: /usr/sbin/visudo -cf %s
       create: yes
  
  - name: Install aur packages
  community.general.pacman:
    name:
      - nerd-fonts-ubuntu-mono
    state: present
    executable: yay
